version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reservation_postgres
    environment:
      POSTGRES_DB: reservation_sys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: baniak2002
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      dockerfile: Dockerfile
    container_name: reservation_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reservation_sys
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: baniak2002
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
